# Generated by Django 4.2.18 on 2025-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.AutoField(help_text='Matricula do aluno', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do aluno', max_length=70)),
                ('dataInicial', models.DateField(help_text='Informe a Data inicial')),
                ('dataFinal', models.DateField(help_text='Informe a Data inicial')),
                ('teste', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
