# Generated by Django 4.2.18 on 2025-02-12 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_rename_codigo_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(default=datetime.datetime(2025, 2, 12, 23, 48, 57, 486970, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 12, 23, 48, 57, 486970, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial'),
        ),
    ]
