# Generated by Django 4.2.18 on 2025-02-28 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_aluno_datafinal_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(help_text='Informe a Data inicial', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='Informe a Data inicial'),
        ),
    ]
