# Generated by Django 4.2.18 on 2025-02-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_alter_aluno_datafinal_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='teste',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(blank=True, help_text='Informe a Data inicial', null=True),
        ),
    ]
