# Generated by Django 4.2.18 on 2025-02-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '002_alter_tituo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='codigo',
            field=models.IntegerField(help_text='Código do titulo', primary_key=True, serialize=False),
        ),
    ]
