# Generated by Django 4.2.18 on 2025-02-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutores',
            name='data_registro',
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='Id',
            field=models.AutoField(help_text='Identificação do Instrutor', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='dataNascimento',
            field=models.DateField(blank=True, help_text='Informe a Data de Nascimento do Instrutor', null=True),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='nome',
            field=models.CharField(help_text='Informe a descrição do instrutor', max_length=70),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='rg',
            field=models.CharField(help_text='Informe a região do instrutor', max_length=15, null=True),
        ),
    ]
