# Generated by Django 4.2.18 on 2025-02-12 23:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
        ('aluno', '0003_alter_aluno_datafinal_alter_aluno_datainicial'),
        ('instrutores', '0002_remove_instrutores_data_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('numero', models.AutoField(help_text='Número da Turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Informe o horário da Aula')),
                ('duracaoAula', models.DurationField(help_text='Informe o horário da Aula')),
                ('dataInicial', models.DateField(default=datetime.datetime(2025, 2, 12, 23, 48, 57, 486970, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial')),
                ('dataFinal', models.DateField(default=datetime.datetime(2025, 2, 12, 23, 48, 57, 486970, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial')),
                ('codigoTipoAtividade', models.ForeignKey(blank=True, help_text='codigo do tipo de atividade da Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipodeatividade.tipodeatividade')),
                ('idInstrutor', models.ForeignKey(help_text='Identidade do Instrutor da Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrutores.instrutores')),
                ('matriculaMonitor', models.ForeignKey(blank=True, help_text='Matrícula do Monitor da Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
            ],
        ),
    ]
