# Generated by Django 4.2.18 on 2025-02-14 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_datafinal_alter_aluno_datainicial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='dataFinal',
            field=models.DateField(default=datetime.datetime(2025, 2, 14, 23, 11, 54, 269321, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 14, 23, 11, 54, 269321, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial'),
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', models.DateField(default=django.utils.timezone.now, help_text='Data da Matrícula do Aluno na Turma')),
                ('data_fim_matricula', models.DateField(blank=True, help_text='Data de fim de Matrícula doAluno na turma')),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do Aluno da Turma', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('numero_turma', models.ForeignKey(help_text='Número da Turma do Aluno', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas')),
            ],
        ),
    ]
