# Generated by Django 4.2.18 on 2025-02-14 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
        ('instrutores', '0002_remove_instrutores_data_registro_and_more'),
        ('aluno', '0006_alter_aluno_datafinal_alter_aluno_datainicial'),
        ('turmas', '0003_alter_turmas_datafinal_alter_turmas_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmaaluno',
            name='data_fim_matricula',
            field=models.DateField(blank=True, help_text='Data fim de matrícula do aluno.', null=True),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='data_inicio_matricula',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data da matrícula do aluno.'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='matricula_aluno',
            field=models.ForeignKey(help_text='Matrícula do aluno.', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe a turma do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora em que a hora da aula da Turma')),
                ('duracao_aula', models.SmallIntegerField(default=30, help_text='Informe a duração da aula da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 59, 22, 367223, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 59, 22, 367223, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma')),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('id_instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutores')),
                ('matricula_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='numero_turma',
            field=models.ForeignKey(help_text='Turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
        migrations.DeleteModel(
            name='Turmas',
        ),
    ]
